connclose(conn, "asynch resolve failed")