PyErr_Format(PyExc_TypeError, "Dataset %s not found", name);